spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.25.80:8858
        port: 8200

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8200
