server:
  port: 8300
spring:
  cloud:
    gateway:
      routes:
        - id: service-email-8100
          uri: lb://service-email-8100
          predicates:
            - Path=/api/user
          filters:
            - StripPrefix=1
